/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ConexiónDB;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;      
import javax.swing.JOptionPane;

/**
 *
 * @author SOR LONDOÑO
 */
public class JFrameConexiónDBSwing extends javax.swing.JFrame {
    
   public static final String URL ="jdbc:mysql://localhost:3306/colegio";
   public static final String USERNAME ="root";
   public static final String PASSWORD ="43987176";
   
   PreparedStatement ps;
   ResultSet rs;
   
   
    public static Connection getConection()
    {
        Connection con =null;
        
        try{
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection(URL,USERNAME,PASSWORD);
            JOptionPane.showMessageDialog(null, "Conexión Exitosa");
        
        }catch(Exception e){
            System.out.println(e);
        }
        return con;
        }
    
    private void limpiarCajas(){
       txtClave.setText(null);
       txtNombres.setText(null);
       txtApellidos.setText(null);
       cboGrado.setSelectedIndex(0);
       cboJornada.setSelectedIndex(0);
       cboAsignaturas.setSelectedIndex(0);
       cboDesempeño.setSelectedIndex(0);
    }
    
    /**
     * Creates new form JFrameConexiónDBSwingprivate 
     */
    public JFrameConexiónDBSwing() {
        initComponents();
        txtId.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        cboGrado = new javax.swing.JComboBox<>();
        cboJornada = new javax.swing.JComboBox<>();
        cboAsignaturas = new javax.swing.JComboBox<>();
        cboDesempeño = new javax.swing.JComboBox<>();
        btnGuardarEstudiante = new javax.swing.JButton();
        btnModificarEstudiante = new javax.swing.JButton();
        btnEliminarEstudiante = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnBuscarEstudiante = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Clave");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 70, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombres");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Apellidos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 80, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Grado");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 60, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Jornada");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 70, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Asignatura");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 90, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Desempeño");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 90, 30));
        getContentPane().add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 160, 30));
        getContentPane().add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 210, 30));
        getContentPane().add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 210, 30));

        cboGrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione>", "Primero", "Segundo", "Tercero", "Cuarto", "Quinto", "Sexto", "Séptimo", "Octavo", "Noveno", "Décimo", "Undécimo" }));
        getContentPane().add(cboGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 140, 30));

        cboJornada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione>", "Mañana", "Tarde", "Completa", "Única" }));
        getContentPane().add(cboJornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 140, 30));

        cboAsignaturas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione>", "Matemáticas", "Español", "Ciencias Sociales", "Ciencias Naturales", "Inglés", "Tecnología e Informática", "Cívica", "Educación Física", "Educación Religiosa", "Educación Artística", "Ética", "Emprendimiento", "Catedra de la paz" }));
        getContentPane().add(cboAsignaturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 160, 30));

        cboDesempeño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione>", "Superior", "Alto", "Básico", "Bajo" }));
        getContentPane().add(cboDesempeño, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 160, 30));

        btnGuardarEstudiante.setBackground(new java.awt.Color(102, 102, 102));
        btnGuardarEstudiante.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardarEstudiante.setText("Guardar");
        btnGuardarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEstudianteActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, 40));

        btnModificarEstudiante.setBackground(new java.awt.Color(102, 102, 102));
        btnModificarEstudiante.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModificarEstudiante.setText("Modificar");
        btnModificarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarEstudianteActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 100, 40));

        btnEliminarEstudiante.setBackground(new java.awt.Color(102, 102, 102));
        btnEliminarEstudiante.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminarEstudiante.setText("Eliminar");
        btnEliminarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEstudianteActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, 40));

        btnLimpiar.setBackground(new java.awt.Color(102, 102, 102));
        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, 40));

        btnBuscarEstudiante.setBackground(new java.awt.Color(204, 204, 204));
        btnBuscarEstudiante.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBuscarEstudiante.setText("Buscar");
        btnBuscarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEstudianteActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, 30));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 30, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEstudianteActionPerformed
        // TODO add your handling code here:
        Connection con;
        
        try{
             con = getConection();
             
             ps = con.prepareStatement("INSERT INTO estudiante(clave,nombres,apellidos,grado,jornada,asignatura,desempeño)VALUES (?,?,?,?,?,?,?)");
             ps.setString(1, txtClave.getText());
             ps.setString(2, txtNombres.getText());
             ps.setString(3, txtApellidos.getText());
             ps.setString(4, cboGrado.getSelectedItem().toString());
             ps.setString(5, cboJornada.getSelectedItem().toString());
             ps.setString(6, cboAsignaturas.getSelectedItem().toString());
             ps.setString(7, cboDesempeño.getSelectedItem().toString());
             
             int res = ps.executeUpdate();
             
             if(res>0){
                 JOptionPane.showMessageDialog(null, "Datos Guardados");
                 limpiarCajas();
             }else{
             JOptionPane.showMessageDialog(null, "Error al guardar");
             limpiarCajas();
             }
             
             con.close();
       }catch(Exception e){
           System.err.println();
       }
    }//GEN-LAST:event_btnGuardarEstudianteActionPerformed

    private void btnBuscarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEstudianteActionPerformed
        // TODO add your handling code here:
        
        Connection con;
        
        try{
                con = getConection();
              
                ps = con.prepareStatement("SELECT * FROM estudiante WHERE clave = ?");
                ps.setString(1, txtClave.getText());
              
                rs = ps.executeQuery();
              
                if(rs.next()){
                 txtId.setText(rs.getString("id"));
                 txtNombres.setText(rs.getString("nombres"));
                 txtApellidos.setText(rs.getString("apellidos"));
                 cboGrado.setSelectedItem(rs.getString("grado"));
                 cboJornada.setSelectedItem(rs.getString("jornada"));
                 cboAsignaturas.setSelectedItem(rs.getString("asignatura"));
                 cboDesempeño.setSelectedItem(rs.getString("desempeño"));
                }else{
                 
                     JOptionPane.showMessageDialog(null, "No existe una persona con esa clave");
                }
             
        }catch(Exception e){
        System.out.println(e);
        }
    }//GEN-LAST:event_btnBuscarEstudianteActionPerformed

    private void btnModificarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEstudianteActionPerformed
        // TODO add your handling code here:
        Connection con;
        
        try{
             con = getConection();
             
             ps = con.prepareStatement("UPDATE estudiante SET clave=?,nombres=?,apellidos=?,grado=?,jornada=?,asignatura=?,desempeño=?, where id=?");
             ps.setInt(1,Integer.parseInt(txtClave.getText()));
             ps.setString(2, txtNombres.getText());
             ps.setString(3, txtApellidos.getText());
             ps.setString(4, cboGrado.getSelectedItem().toString());
             ps.setString(5, cboJornada.getSelectedItem().toString());
             ps.setString(6, cboAsignaturas.getSelectedItem().toString());
             ps.setString(7, cboDesempeño.getSelectedItem().toString());
             
             int res = ps.executeUpdate();
             
             if(res>0){
                 JOptionPane.showMessageDialog(null, "Datos Modificados");
                 limpiarCajas();
             }else{
             JOptionPane.showMessageDialog(null, "Error al modificar los datos");
             limpiarCajas();
             }
             
             con.close();
       }catch(Exception e){
           System.err.println();
       }
    }//GEN-LAST:event_btnModificarEstudianteActionPerformed

    private void btnEliminarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEstudianteActionPerformed
        // TODO add your handling code here:
        Connection con;
        
        try{
             con = getConection();
             
             ps = con.prepareStatement("DELETE FROM estudiante where id=?");
             ps.setInt(1,Integer.parseInt(txtId.getText()));
             
             
             int res = ps.executeUpdate();
             
             if(res>0){
                 JOptionPane.showMessageDialog(null, "Datos Eliminados");
                 limpiarCajas();
             }else{
             JOptionPane.showMessageDialog(null, "Error al eliminar los datos");
             limpiarCajas();
             }
             
             con.close();
             
        }catch(Exception e){
           System.err.println();
        }
    }//GEN-LAST:event_btnEliminarEstudianteActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCajas();
    }//GEN-LAST:event_btnLimpiarActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameConexiónDBSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameConexiónDBSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameConexiónDBSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameConexiónDBSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameConexiónDBSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEstudiante;
    private javax.swing.JButton btnEliminarEstudiante;
    private javax.swing.JButton btnGuardarEstudiante;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificarEstudiante;
    private javax.swing.JComboBox<String> cboAsignaturas;
    private javax.swing.JComboBox<String> cboDesempeño;
    private javax.swing.JComboBox<String> cboGrado;
    private javax.swing.JComboBox<String> cboJornada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
